services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server

  redis:
    image: redis:alpine
    container_name: 99-redis
    restart: always

  server:
    image: ghcr.io/benpaul2002/99/server:latest
    restart: always
    depends_on:
      - redis
    env_file:
      - server/.env

  client:
    image: ghcr.io/benpaul2002/99/client:latest
    restart: always
    depends_on:
      - server